### ISSUE TITLE
Apache www-data user should be added to {{ nagios_group }}

### ISSUE THREAD

**Issue by mm0** [sdarwin/Ansible-Nagios#1]
Under the Reports section in the web sidebar there are two items, notifications and event log, that are inaccessible with the current configuration as the apache2 web user (default: www-data) does not belong to the `nagios_group`(nagios), causing a permission denied error.  

Simply adding something like this is necessary for this error to go away:
```
  - name: Add www-data user to nagios group
    user: append=yes user=www-data groups="{{ nagios_group }}"
```

**Comment by sdarwin** [comment]
Hi Matt,
I have just re-tested and that problem is not appearing.
If you hover the mouse over the links you mentioned, they are:
/nagios/cgi-bin/notifications.cgi
/nagios/cgi-bin/showlog.cgi
In the file system the files have these permissions:
-rwxrwxr-x 1 nagios nagios 244504 Dec 22 12:12 /usr/local/nagios/sbin/notifications.cgi
-rwxrwxr-x 1 nagios nagios 240384 Dec 22 12:12 /usr/local/nagios/sbin/showlog.cgi
Notice the cgi files are globally executable, and not -rwx------ or something.
Group permissions in /etc/group:
```
nagcmd:x:1003:nagios,www-data
```
Please tell me:
which exact operating system and version?
what are the file permissions of notifications.cgi and showlog.cgi?
what is the error message? any errors in the web logs?
are you logging into the web portal as "nagiosadmin"?
any customizations to the ansible playbook, or the server?  what about a fresh installation on a new vm?

**Comment by mm0** [comment]
Hi, I believe that I am wrong about needing to add the www-data user to the group, instead I think this might be an issue with a newer init script.  I am testing on Ubuntu 16.04, with the following variables:

```yaml
      nagios_url: "https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.2.4.tar.gz",
      nagios_src: "nagios-4.2.4",
      nagios_pluginsurl: "http://www.nagios-plugins.org/download/nagios-plugins-2.1.4.tar.gz",
      nagios_pluginssrc: "nagios-plugins-2.1.4"
```

I am able to log in to the web portal, please see attachments for description of the error.

My current solution is to add the following as a post_task:  

```yaml
  - name: Fix init script to chmod log file
    lineinfile:
      regexp: 'chmod 0644 $NagiosVarDir/nagios.log $NagiosRetentionFile'
      line: 'chmod 0644 $NagiosVarDir/nagios.log $NagiosRetentionFile'
      insertafter: '.*touch $NagiosVarDir/nagios.log $NagiosRetentionFile'
      dest: /etc/init.d/nagios
```

![screen shot 2016-12-22 at 3 32 44 pm](https://cloud.githubusercontent.com/assets/4008256/21443691/2f28c3fa-c85c-11e6-9011-9acc03a657df.png)
