### ISSUE TITLE
unable to see dashboard

### ISSUE THREAD

**Issue by saireddyavs** [sdarwin/Ansible-Nagios#9]
i have ran the code using 
- roles
   - {role: 'nagios_install', run_nagios_client: true}

where nagios install have all the files from your repo

playbook executed successfully  but i am unable to see dashboard

i have added 
[monitoring-servers]
52.207.75.159

on 52.207.75.159/nagios/ i am ubale to see dashboard  getting problem loading page  

and when tried to run code again i have got other error

TASK [nagios_install : NRPE config file] *******************************************************************************
fatal: [52.207.75.159]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_all_ipv4_addresses'"}

**Comment by saireddyavs** [comment]
TASK [nagios_install : NRPE config file] *******************************************************************************
fatal: [52.207.75.159]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'monitoring-servers'"}

**Comment by sdarwin** [comment]
Hi Avuluri,

You wrote:
```
i have ran the code using
roles
{role: 'nagios_install', run_nagios_client: true}
```

You should run the full playbook, like /default.yml, which includes the server part also.
```
- hosts: all
  become: true
  roles:
    - {role: 'sdarwin.nagios', run_nagios_client: true}
- hosts: monitoring-servers
  become: true
  roles:
    - {role: 'sdarwin.nagios', run_nagios_server: true}
```

**Comment by saireddyavs** [comment]
hi sam


TASK [nagios_install : NRPE config file] *******************************************************************************
fatal: [52.207.75.159]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_all_ipv4_addresses'"}


still i have got this error

**Comment by saireddyavs** [comment]
my code
```
  - hosts : webservers

    remote_user: ubuntu
    become: true
    gather_facts: yes
    become_method: sudo



    roles:
        - {role: 'nagios_install', run_nagios_client: true}


  - hosts: monitoring-servers
    become: true
    remote_user: ubuntu

    roles:
        - {role: 'nagios_install', run_nagios_server: true}

```

i am running it on ec2 hosts

my /etc/ansible/hosts file

```
[webservers]
52.207.75.159
[monitoring-servers]
52-207-75-159
```
